// HTML elements
const container = document.getElementById("container");
const registerbtn = document.getElementById("register");
const loginbtn = document.getElementById("login");

// Toggle sign-up and sign-in
registerbtn.addEventListener("click", () => {
  container.classList.add("active");
});

loginbtn.addEventListener("click", () => {
  container.classList.remove("active");
});

// Handle sign-in functionality
document.querySelector(".sign-in form").addEventListener("submit", (event) => {
  event.preventDefault(); // Prevent form submission
  const username = document.getElementById("username").value.trim();
  const password = document.getElementById("password").value.trim();

  if (username && password) {
    // Fetch the user from API
    fetch(`https://todoliist.runasp.net/api/User/GetUser?UserName=${username}&Password=${password}`)
      .then((response) => {
        if (!response.ok) {
          throw new Error("Invalid username or password");
        }
        return response.json();
      })
      .then((user) => {
        // Successful login, store userID in localStorage
        localStorage.setItem("userID", user.userID);
        console.log("Login successful:", user);
        window.location.href = "home_page.html"; // Redirect to home page
      })
      .catch((error) => {
        console.error("Error during login:", error);
        alert("Invalid username or password. Please try again."); // Show error
      });
  } else {
    alert("Please enter both username and password.");
  }
});



document.addEventListener('DOMContentLoaded', function () {
  // الكود هنا بعد تحميل الصفحة بالكامل
  document.getElementById("sign-up-form").addEventListener("submit", function (event) {
    event.preventDefault(); // Prevent form submission

    const username = document.getElementById("sign-up-user").value.trim();
    const password = document.getElementById("sign-up-pass").value.trim();
    const confirmPassword = document.getElementById("sign-up-ConPass").value.trim();

    // Validate inputs
    if (username === "" || password === "" || confirmPassword === "") {
      alert("Please fill out all fields.");
      return;
    }

    // Check if passwords match
    if (password !== confirmPassword) {
      alert("Passwords do not match.");
      return;
    }

    // Create user data object
    const newUser = {
      userID: 0, // This can be auto-generated by the server
      userName: username,
      password: password
    };

    // Send POST request to register the user
    fetch('https://todoliist.runasp.net/api/User/AddNewUser', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(newUser)
    })
    .then((response) => {
      if (!response.ok) {
        throw new Error('Failed to sign up. Please try again.');
      }
      return response.json();
    })
    .then((data) => {
      console.log('User created successfully:', data);
      alert('Sign Up successful!'); // Show success message
      // Optionally, redirect the user to the login page or home page
      window.location.href = 'login_page.html'; // Replace with your desired page
    })
    .catch((error) => {
      console.error('Error during sign up:', error);
      alert('Error: ' + error.message);
    });
  });
});
